version: '3.6'

services:
  db-postgres:
    image: postgres:alpine
    container_name: db-postgres
    ports:
      - 5433:5432
    environment:
      - DB_NAME:postgres
      - DB_USER:postgres
      - DB_PASS:Postgres
    expose:
      - 5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  backend:
    image: sequelize-boilerplate
    ports: 
      - 3000:3000
    volumes:
      - /Users/radhakotecha/Desktop/sequelize-boilerplate:/sequelize-boilerplate
    depends_on: 
      - db-postgres